### ISSUE TITLE
cannot import name 'ChatGPT' from 'chatgpt_wrapper'

### ISSUE THREAD

**Issue by Bykow** [omegaui/linux-voice-control#11]
Hello, 

Just did a fresh install of linux-voice-control, through cloning the repo and running the `install.sh` script. 

I'm getting this error when trying to launch either the gui or the cli. 

Here is there the error:

```
Traceback (most recent call last):
  File "/home/bykow/lvc-bin/main.py", line 19, in <module>
    import chatgpt_port
  File "/home/bykow/lvc-bin/chatgpt_port.py", line 5, in <module>
    from chatgpt_wrapper import ChatGPT
ImportError: cannot import name 'ChatGPT' from 'chatgpt_wrapper' (/home/bykow/.local/lib/python3.10/site-packages/chatgpt_wrapper/__init__.py)
```

**Comment by omegaui** [comment]
@Bykow 
The error is arising from `chatgpt_wrapper`  library, try using an older version of the lib!

**Comment by Bykow** [comment]
Hello, currently not in front the computer before he t week.
could you advise how to do this? I don't recall installing it manually.

Using arch if that matters in some way

**Comment by Bykow** [comment]
Hello, currently not in front the computer before he t week.
could you advise how to do this? I don't recall installing it manually.

Using arch if that matters in some way

**Comment by Bykow** [comment]
@omegaui any news ? :pray:

**Comment by Hwatwasthat** [comment]
Hello I'm getting this same error. It's unclear as this was installed as part of the install process, not separately by myself.

**Comment by omegaui** [comment]
@Hwatwasthat 
@Bykow 
All Set!

**Comment by thhart** [comment]
Cloned and installed today, but error still remains, is the code already updated?
