### ISSUE TITLE
LangChain LLM Agent 

### ISSUE THREAD

**Issue by Microwave-WYB** [omegaui/linux-voice-control#12]
LangChain can provide external tools to LLMs. Maybe we write some tools to let LLMs like GPT3.5 decide which one to use

**Comment by omegaui** [comment]
@Microwave-WYB 

`linux-voice-control` is a **minimal manually-managed** voice control system.
This is not based on automation or chatbots, but to provide a simple Speech to Action feature.

🚀 Yes! LangChain can be used but not in this project, if we think forward to create a chatbot based feature, then, we need to create another project for that.

As well as this project is not based on any chat based language model, ChatGPT is just an extra asset used in linux-voice-control.

❣️ Thanks for your valuable suggestion, using LangChain can provide seamless integration but then, we also need to train a model that can understand task execution.

I am leaving this issue open as this is a good start point to create a better seamless version of this project.
Here is the documentation link for anyone who is looking forward to create it using [conversational approach].(https://python.langchain.com/en/latest/modules/agents/agents/examples/conversational_agent.html)
