### ISSUE TITLE
Transcribing very slow and only works in live mode

### ISSUE THREAD

**Issue by stuckinthe** [omegaui/linux-voice-control#14]
I had the same errors as in this post.

https://github.com/omegaui/linux-voice-control/issues/13#issuecomment-1682948397

I didn't do the install file as I just ran python3 main.py. It eventually started and I was in live mode and I did a test sentence: testing 1,2,3 and it transcribed it properly but it took about 5+ minutes to transcribe. I'm not sure how you could work in live mode since it picks up everything that is spoken.

I also tried python3 master_control_mode_setup.py. When I run this, it doesn't pickup any speech and eventually it will say transcribing and it takes 5+ minutes with no results.

I want to use linux voice control to control my RPi 3+ using your program. Maybe my system doesn't have enough power to run Kodi and your program. Since I need widevine, I am running in 32 bit mode and it was a dog to get pytorch, torchvision, and torchaudio compiled on a 32 bit system. I had to turn alot off like Kaldi, etc just to get it to compile and then it took about 24 hours.

**Comment by omegaui** [comment]
@stuckinthe 
Sorry for the late response,
Do you have mpvlib installed?
also, can you specify your system specs,
also what type of storage device you are using?

**Comment by stuckinthe** [comment]
Yes, I have mpvlib installed. I am running a Rpi3+ with a memory card. I just don't think the Rpi has enough to handle. Also, I'm not sure torch audio complied properly since I'm running 32 bit. 

I did a test script using pocketsphhinx at is was slow as well. Vosk-api works since it has a smaller dictionary.
