### ISSUE TITLE
I get this error post installation

### ISSUE THREAD

**Issue by krafairus** [omegaui/linux-voice-control#19]
I installed linux-voice-control on debian 12 using pipewire, and it gives me the following message when running the linux-voice-control command:
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
🐧 loading commands file ...
🚀 voice control ready ... responding every 3 seconds
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
You: its the voice going with us were looking at it
probability: ('write an email', 45)
>>> Unrecognized command
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
You: im not going to get it its all im not going to get it
probability: ('write an email', 43)
>>> Unrecognized command
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
listening ...
saving audio ...
transcribing audio data ...
analyzing results ...
You: i need to talk about this ill see you later
probability: ('see you later alex', 86)
>>> Unrecognized command

Then it goes on and on, more logs about the same thing from: 
listening...
saving audio...
transcribing audio data...
analyzing results...
You: those are everything
probability: ('open instagram', 42)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
You: transform the bigger kilograms
probability: ('open instagram', 45)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
You: you usually have toville
probability: ('see you later alex', 49)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
You: rockkeeps over the front end does it look like a pussy please subscribe
probability: ('open editor', 50)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
You: I like to get my bag in
probability: ('write an email', 43)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
listening...
saving audio...
transcribing audio data...
analyzing results...
You: alone
probability: ('write an email', 54)
>>> Unrecognized command
listening...
saving audio...
transcribing audio data...
analyzing results...
listening...
saving audio...
transcribing audio data...
analyzing results...
listening...
saving audio...
transcribing audio data...
analyzing results...
You: but that's what's doing here honestly
probability: ('open firefox', 45)
>>> Unrecognized command
listening...

After finishing, the execution of the command ends, and if I run linux-voice-control again, it starts doing the same thing again.

**Comment by krafairus** [comment]
[CODE]System:
  Kernel: 6.1.0-21-amd64 [6.1.90-1] arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-6.1.0-21-amd64 root=UUID=<filter> ro quiet splash
    init=/lib/systemd/systemd
  Desktop: KDE Plasma v: 5.27.5 wm: kwin_x11 vt: 7 dm: SDDM Distro: MX-23.3_KDE_x64 Libretto May
    19 2024 base: Debian GNU/Linux 12 (bookworm)
Machine:
  Type: Laptop System: Hewlett-Packard product: HP 240 G7 Notebook PC v: N/A
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: Hewlett-Packard model: 868A v: 63.13 serial: <superuser required> UEFI: AMI v: F.10
    date: 09/18/2020
Battery:
  ID-1: BAT0 charge: 29.5 Wh (79.1%) condition: 37.3/37.3 Wh (100.0%) volts: 11.8 min: 11.6
    model: Hewlett-Packard Primary type: Li-ion serial: <filter> status: discharging
CPU:
  Info: model: Intel Core i3-1005G1 bits: 64 type: MT MCP arch: Ice Lake gen: core 10 level: v4
    note: check built: 2019-21 process: Intel 10nm family: 6 model-id: 0x7E (126) stepping: 5
    microcode: 0xC2
  Topology: cpus: 1x cores: 2 tpc: 2 threads: 4 smt: enabled cache: L1: 160 KiB
    desc: d-2x48 KiB; i-2x32 KiB L2: 1024 KiB desc: 2x512 KiB L3: 4 MiB desc: 1x4 MiB
  Speed (MHz): avg: 1075 high: 1302 min/max: 400/3400 scaling: driver: intel_pstate
    governor: powersave cores: 1: 400 2: 1300 3: 1300 4: 1302 bogomips: 9523
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling mitigation: Microcode
  Type: itlb_multihit status: KVM: VMX disabled
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data mitigation: Clear CPU buffers; SMT vulnerable
  Type: reg_file_data_sampling status: Not affected
  Type: retbleed mitigation: Enhanced IBRS
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Enhanced / Automatic IBRS; IBPB: conditional; RSB filling;
    PBRSB-eIBRS: SW sequence; BHI: SW loop, KVM: SW loop
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort status: Not affected
Graphics:
  Device-1: Intel Iris Plus Graphics G1 vendor: Hewlett-Packard driver: i915 v: kernel arch: Gen-11
    process: Intel 10nm built: 2019-21 ports: active: eDP-1 empty: DP-1, DP-2, DP-3, DP-4, HDMI-A-1
    bus-ID: 00:02.0 chip-ID: 8086:8a56 class-ID: 0300
  Device-2: Cheng Uei Precision Industry (Foxlink) HP TrueVision HD Camera type: USB
    driver: uvcvideo bus-ID: 1-6:2 chip-ID: 05c8:03d2 class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 compositor: kwin_x11 driver: X:
    loaded: modesetting unloaded: fbdev,vesa dri: iris gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.21x7.99") s-diag: 414mm (16.31")
  Monitor-1: eDP-1 model: BOE Display 0x0697 built: 2015 res: 1366x768 hz: 60 dpi: 112 gamma: 1.2
    size: 309x173mm (12.17x6.81") diag: 354mm (13.9") ratio: 16:9 modes: 1366x768
  API: OpenGL v: 4.6 Mesa 23.1.2-1~mx23ahs renderer: Mesa Intel UHD Graphics (ICL GT1)
    direct-render: Yes
Audio:
  Device-1: Intel Ice Lake-LP Smart Sound Audio vendor: Hewlett-Packard driver: snd_hda_intel
    v: kernel alternate: snd_sof_pci_intel_icl bus-ID: 00:1f.3 chip-ID: 8086:34c8 class-ID: 0403
  API: ALSA v: k6.1.0-21-amd64 status: kernel-api tools: alsamixer,amixer
  Server-1: JACK v: 1.9.21 status: off tools: jack_control
  Server-2: PipeWire v: 1.0.0 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin 4: pw-jack type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Hewlett-Packard
    driver: r8169 v: kernel pcie: speed: Unknown lanes: 63 link-max: gen: 6 speed: 64 GT/s port: 4000
    bus-ID: 02:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: eth0 state: down mac: <filter>
  Device-2: Realtek RTL8821CE 802.11ac PCIe Wireless Network Adapter vendor: Hewlett-Packard
    driver: rtw_8821ce v: N/A modules: rtw88_8821ce,wl,rtl8821ce pcie: gen: 1 speed: 2.5 GT/s
    lanes: 1 port: 3000 bus-ID: 03:00.0 chip-ID: 10ec:c821 class-ID: 0280
  IF: wlan0 state: up mac: <filter>
  IF-ID-1: docker0 state: down mac: <filter>
Bluetooth:
  Device-1: Realtek Bluetooth 4.2 Adapter type: USB driver: btusb v: 0.8 bus-ID: 1-10:3
    chip-ID: 0bda:b00a class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 1 state: down bt-service: enabled,running rfk-block:
    hardware: no software: yes address: <filter>
  Info: acl-mtu: 1021:8 sco-mtu: 255:12 link-policy: rswitch hold sniff park
    link-mode: peripheral accept
RAID:
  Hardware-1: Intel 82801 Mobile SATA Controller [RAID mode] driver: ahci v: 3.0 port: 5060
    bus-ID: 00:17.0 chip-ID: 8086:282a rev: N/A class-ID: 0104
Drives:
  Local Storage: total: 931.51 GiB used: 69.7 GiB (7.5%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/sda maj-min: 8:0 vendor: Toshiba model: MQ04ABF100 size: 931.51 GiB block-size:
    physical: 4096 B logical: 512 B speed: 6.0 Gb/s type: HDD rpm: 5400 serial: <filter> rev: 7C
    scheme: GPT
Partition:
  ID-1: / raw-size: 432.45 GiB size: 424.59 GiB (98.18%) used: 69.7 GiB (16.4%) fs: ext4
    dev: /dev/sda7 maj-min: 8:7
  ID-2: /boot/efi raw-size: 1024 MiB size: 1022 MiB (99.80%) used: 432 KiB (0.0%) fs: vfat
    dev: /dev/sda5 maj-min: 8:5
Swap:
  Kernel: swappiness: 15 (default 60) cache-pressure: 100 (default)
  ID-1: swap-1 type: partition size: 6 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/sda6
    maj-min: 8:6
Sensors:
  System Temperatures: cpu: 58.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2998 pm: dpkg pkgs: 2984 libs: 1706 tools: apt,apt-get,aptitude,nala pm: rpm pkgs: 0
    pm: flatpak pkgs: 14
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/debian-stable-updates.list
    1: deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
  Active apt repos in: /etc/apt/sources.list.d/debian.list
    1: deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
    2: deb http://security.debian.org/debian-security bookworm-security main contrib non-free non-free-firmware
  Active apt repos in: /etc/apt/sources.list.d/docker.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/mx.list
    1: deb http://mirror.cedia.org.ec/mx-workspace/mx/repo/ bookworm main non-free
    2: deb http://mirror.cedia.org.ec/mx-workspace/mx/repo/ bookworm ahs
  Active apt repos in: /etc/apt/sources.list.d/spotify.list
    1: deb http://repository.spotify.com stable non-free
  Active apt repos in: /etc/apt/sources.list.d/sublime-text.list
    1: deb https://download.sublimetext.com/ apt/stable/
  Active apt repos in: /etc/apt/sources.list.d/winehq-bookworm.sources
    1: deb [arch=amd64 i386] https://dl.winehq.org/wine-builds/debian bookworm main
Info:
  Processes: 209 Uptime: 16m wakeups: 1 Memory: 7.45 GiB used: 3.45 GiB (46.3%) Init: systemd
  v: 252 target: graphical (5) default: graphical tool: systemctl Compilers: gcc: 12.2.0 alt: 12
  Client: shell wrapper v: 5.2.15-release inxi: 3.3.26
Boot Mode: UEFI[/CODE]

**Comment by omegaui** [comment]
@krafairus 
Hi, I'm also on Debain 12, there's seem to be an initialization warning when you run linux-voice-control which is fine I think you can ignore it because I see the program is able to collect your voice to find a matching command.

I suggest you take a look at how linux-voice-control is actually designed to work, it will not respond to any text you say, but to only those you define in the lvc-commands.json file, see [usage](https://github.com/omegaui/linux-voice-control#-usage--install).
