### ISSUE TITLE
issue to install

### ISSUE THREAD

**Issue by Dav-d** [omegaui/linux-voice-control#7]
HI, 
I try to install LVC on a gnome/Manjaro but unfortunalty I've got an issue when I run linux-voice-control :
`> linux-voice-control     
torchvision is not available - cannot save figures
Traceback (most recent call last):
  File "/home/david/lvc-bin/main.py", line 16, in <module>
    import command_manager
  File "/home/david/lvc-bin/command_manager.py", line 19, in <module>
    from voice_feedback import give_execution_feedback, speak
  File "/home/david/lvc-bin/voice_feedback.py", line 4, in <module>
    import mpv
  File "/home/david/.local/lib/python3.10/site-packages/mpv.py", line 190, in <module>
    _handle_func('mpv_detach_destroy', [], c_int)
  File "/home/david/.local/lib/python3.10/site-packages/mpv.py", line 166, in _handle_func
    func = getattr(backend, name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libmpv.so: undefined symbol: mpv_detach_destroy 
`

Requirements seem statisfied :

`> ./install.sh                           
pip installing requirements.txt ...
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting git+https://github.com/openai/whisper.git (from -r requirements.txt (line 9))
  Cloning https://github.com/openai/whisper.git to /tmp/pip-req-build-lk3v4li2
  Running command git clone --filter=blob:none --quiet https://github.com/openai/whisper.git /tmp/pip-req-build-lk3v4li2
  Resolved https://github.com/openai/whisper.git to commit 0b5dcfdef7ec04250b76e13f1630e32b0935ce76
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (1.23.5)
Requirement already satisfied: tqdm in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (4.64.1)
Requirement already satisfied: more-itertools in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (9.0.0)
Requirement already satisfied: transformers>=4.19.0 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (4.25.1)
Requirement already satisfied: ffmpeg-python==0.2.0 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.2.0)
Requirement already satisfied: click~=8.1.3 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (8.1.3)
Requirement already satisfied: pyaudio~=0.2.11 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.2.12)
Requirement already satisfied: pydub in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (0.25.1)
Requirement already satisfied: torch in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (1.13.1)
Requirement already satisfied: thefuzz~=0.19.0 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (0.19.0)
Requirement already satisfied: termcolor~=2.0.1 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (2.0.1)
Requirement already satisfied: gTTS~=2.3.0 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (2.3.0)
Requirement already satisfied: mpv~=0.1 in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (0.1)
Requirement already satisfied: speechbrain in /home/david/.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (0.5.13)
Requirement already satisfied: future in /usr/lib/python3.10/site-packages (from ffmpeg-python==0.2.0->-r requirements.txt (line 5)) (0.18.2)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (21.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (2022.10.31)
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (2.28.1)
Requirement already satisfied: filelock in /usr/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (3.8.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (6.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/david/.local/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.10.0 in /home/david/.local/lib/python3.10/site-packages (from transformers>=4.19.0->-r requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: typing-extensions in /usr/lib/python3.10/site-packages (from torch->-r requirements.txt (line 11)) (4.4.0)
Requirement already satisfied: nvidia-cublas-cu11==11.10.3.66 in /home/david/.local/lib/python3.10/site-packages (from torch->-r requirements.txt (line 11)) (11.10.3.66)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/david/.local/lib/python3.10/site-packages (from torch->-r requirements.txt (line 11)) (11.7.99)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/david/.local/lib/python3.10/site-packages (from torch->-r requirements.txt (line 11)) (11.7.99)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/david/.local/lib/python3.10/site-packages (from torch->-r requirements.txt (line 11)) (8.5.0.96)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (65.6.3)
Requirement already satisfied: wheel in /usr/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (0.38.4)
Requirement already satisfied: six~=1.16.0 in /usr/lib/python3.10/site-packages (from gTTS~=2.3.0->-r requirements.txt (line 15)) (1.16.0)
Requirement already satisfied: sentencepiece in /home/david/.local/lib/python3.10/site-packages (from speechbrain->-r requirements.txt (line 17)) (0.1.97)
Requirement already satisfied: joblib in /home/david/.local/lib/python3.10/site-packages (from speechbrain->-r requirements.txt (line 17)) (1.2.0)
Requirement already satisfied: scipy in /home/david/.local/lib/python3.10/site-packages (from speechbrain->-r requirements.txt (line 17)) (1.9.3)
Requirement already satisfied: hyperpyyaml in /home/david/.local/lib/python3.10/site-packages (from speechbrain->-r requirements.txt (line 17)) (1.1.0)
Requirement already satisfied: torchaudio in /home/david/.local/lib/python3.10/site-packages (from speechbrain->-r requirements.txt (line 17)) (0.13.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging>=20.0->transformers>=4.19.0->-r requirements.txt (line 4)) (3.0.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 4)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->transformers>=4.19.0->-r requirements.txt (line 4)) (1.26.12)
Requirement already satisfied: ruamel.yaml>=0.17.8 in /usr/lib/python3.10/site-packages (from hyperpyyaml->speechbrain->-r requirements.txt (line 17)) (0.17.21)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6 in /usr/lib/python3.10/site-packages (from ruamel.yaml>=0.17.8->hyperpyyaml->speechbrain->-r requirements.txt (line 17)) (0.2.7)
Requirement already satisfied: appdirs in /usr/lib/python3.10/site-packages (from setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (1.4.4)
Requirement already satisfied: jaraco.text in /usr/lib/python3.10/site-packages (from setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (3.11.0)
Requirement already satisfied: ordered-set in /usr/lib/python3.10/site-packages (from setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (4.1.0)
Requirement already satisfied: tomli in /usr/lib/python3.10/site-packages (from setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (2.0.1)
Requirement already satisfied: validate-pyproject in /usr/lib/python3.10/site-packages (from setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (0.10.1)
Requirement already satisfied: inflect in /usr/lib/python3.10/site-packages (from jaraco.text->setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (6.0.2)
Requirement already satisfied: autocommand in /usr/lib/python3.10/site-packages (from jaraco.text->setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (2.2.2)
Requirement already satisfied: jaraco.functools in /usr/lib/python3.10/site-packages (from jaraco.text->setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (3.5.2)
Requirement already satisfied: jaraco.context>=4.1 in /usr/lib/python3.10/site-packages (from jaraco.text->setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (4.2.0)
Requirement already satisfied: pydantic>=1.9.1 in /usr/lib/python3.10/site-packages (from inflect->jaraco.text->setuptools->nvidia-cublas-cu11==11.10.3.66->torch->-r requirements.txt (line 11)) (1.10.2)
Settings up Linux-Voice-Control (lvc) ...
mkdir: impossible de créer le répertoire « /home/david/lvc-bin »: Le fichier existe
Copying sources and icon to ~/lvc-bin ...
Copying launcher(linux-voice-control) to /usr/bin (requires root access) ...
[sudo] Mot de passe :
Copying default commands and config to ~ ...
All Set
`

Could you help me ?
Regards

**Comment by omegaui** [comment]
@Dav-d 

Sorry for the late reply!
Try reinstalling it from source!
Looks like there is an issue with mpv.
Try reinstalling .
